#ifndef COMMON_H
#define COMMON_H

#include <ultra64.h>

typedef struct WAVE_W {
    unsigned short wave_no;
    int            data;
} WAVE_W;

typedef struct AMEM_W {
    char*          pt;
    unsigned int   size;
    struct AMEM_W* next;
    struct AMEM_W* up;
} AMEM_W;

typedef struct CLS_W {
    struct CLS_W*  next;
    unsigned char  kind;
    unsigned char  pri;
    unsigned short s_pri;
} CLS_W;

typedef struct CLS_2D_W {
    CLS_W           header;
    unsigned int    unk_8;
    unsigned char   unk_c;
    unsigned char   unk_d;
    unsigned char   unk_e;
    unsigned char   unk_f;
    unsigned char   unk_10;
    unsigned char   unk_11;
    unsigned char   unk_12;
    unsigned char   unk_13;
    int             unk_14;
    unsigned short  unk_18;
    unsigned char   unk_1a;
    unsigned char   unk_1b;
    short           unk_1c;
    unsigned char   unk_1e;
    unsigned char   unk_1f;
    short           unk_20;
    unsigned char   unk_22;
    unsigned char   unk_23;
    unsigned char   unk_24;
    unsigned char   unk_25;
    unsigned char   unk_26;
    unsigned char   unk_27;
    unsigned char   unk_28;
    unsigned char   unk_29;
    unsigned char   unk_2a;
    unsigned char   unk_2b;
    float           unk_2c;
    float           unk_30;
    unsigned short* unk_34;
    unsigned int    unk_38;
    unsigned char   unk_3c;
    unsigned char   unk_3d;
    unsigned char   unk_3e;
    unsigned char   unk_3f;
} CLS_2D_W;

typedef struct CLS_MOJI_W {
    CLS_W          header;
    unsigned char  unk_8;
    unsigned char  unk_9;
    unsigned char  unk_a;
    unsigned char  unk_b;
    short          unk_c;
    unsigned char  unk_e;
    unsigned char  unk_f;
    unsigned char  unk_10;
    unsigned char  unk_11;
    unsigned char  unk_12;
    unsigned char  unk_13;
    unsigned char  unk_14;
    unsigned char  unk_15;
    unsigned char  unk_16;
    unsigned char  unk_17;
    unsigned char  unk_18;
    unsigned char  unk_19;
    unsigned char  unk_1a;
    unsigned char  unk_1b;
    unsigned char  unk_1c;
    unsigned char  unk_1d;
    unsigned char  unk_1e;
    unsigned char  unk_1f;
    unsigned char  unk_20;
    unsigned char  unk_21;
    unsigned char  unk_22;
    unsigned char  unk_23;
    unsigned char  unk_24;
    unsigned char  unk_25;
    unsigned char  unk_26;
    unsigned char  unk_27;
    unsigned char  unk_28;
    unsigned char  unk_29;
    unsigned char  unk_2a;
    unsigned char  unk_2b;
    unsigned char  unk_2c;
    unsigned char  unk_2d;
    unsigned char  unk_2e;
    unsigned char  unk_2f;
    unsigned char  unk_30;
    unsigned char  unk_31;
    unsigned char  unk_32;
    unsigned char  unk_33;
    unsigned short unk_34;
    unsigned short unk_36;
    unsigned short unk_38;
    unsigned short unk_3a;
    unsigned char  unk_3c;
    unsigned char  unk_3d;
    unsigned char  unk_3e;
    unsigned char  unk_3f;
    unsigned char  unk_40;
    unsigned char  unk_41;
    unsigned char  unk_42;
    unsigned char  unk_43;
    unsigned char  unk_44;
    unsigned char  unk_45;
    unsigned char  unk_46;
    unsigned char  unk_47;
    unsigned char  unk_48;
    unsigned char  unk_49;
    unsigned char  unk_4a;
    unsigned char  unk_4b;
    unsigned char  unk_4c;
    unsigned char  unk_4d;
    unsigned char  unk_4e;
    unsigned char  unk_4f;
    unsigned char  unk_50;
    unsigned char  unk_51;
    unsigned char  unk_52;
    unsigned char  unk_53;
    unsigned char  unk_54;
    unsigned char  unk_55;
    unsigned char  unk_56;
    unsigned char  unk_57;
    unsigned char  unk_58;
    unsigned char  unk_59;
    unsigned char  unk_5a;
    unsigned char  unk_5b;
    unsigned char  unk_5c;
    unsigned char  unk_5d;
    unsigned char  unk_5e;
    unsigned char  unk_5f;
    unsigned char  unk_60;
    unsigned char  unk_61;
    unsigned char  unk_62;
    unsigned char  unk_63;
    unsigned char  unk_64;
    unsigned char  unk_65;
    unsigned char  unk_66;
    unsigned char  unk_67;
    unsigned char  unk_68;
    unsigned char  unk_69;
    unsigned char  unk_6a;
    unsigned char  unk_6b;
    unsigned char  unk_6c;
    unsigned char  unk_6d;
    unsigned char  unk_6e;
    unsigned char  unk_6f;
    unsigned char  unk_70;
    unsigned char  unk_71;
    unsigned char  unk_72;
    unsigned char  unk_73;
    unsigned char  unk_74;
    unsigned char  unk_75;
    unsigned char  unk_76;
    unsigned char  unk_77;
    unsigned char  unk_78;
    unsigned char  unk_79;
    unsigned char  unk_7a;
    unsigned char  unk_7b;
    unsigned char  unk_7c;
    unsigned char  unk_7d;
    unsigned char  unk_7e;
    unsigned char  unk_7f;
    unsigned char  unk_80;
    unsigned char  unk_81;
    unsigned char  unk_82;
    unsigned char  unk_83;
    unsigned char  unk_84;
    unsigned char  unk_85;
    unsigned char  unk_86;
    unsigned char  unk_87;
    unsigned char  unk_88;
    unsigned char  unk_89;
    unsigned char  unk_8a;
    unsigned char  unk_8b;
    unsigned char  unk_8c;
    unsigned char  unk_8d;
    unsigned char  unk_8e;
    unsigned char  unk_8f;
    unsigned char  unk_90;
    unsigned char  unk_91;
    unsigned char  unk_92;
    unsigned char  unk_93;
    unsigned char  unk_94;
    unsigned char  unk_95;
    unsigned char  unk_96;
    unsigned char  unk_97;
    unsigned char  unk_98;
    unsigned char  unk_99;
    unsigned char  unk_9a;
    unsigned char  unk_9b;
    unsigned char  unk_9c;
    unsigned char  unk_9d;
    unsigned char  unk_9e;
    unsigned char  unk_9f;
    unsigned char  unk_a0;
    unsigned char  unk_a1;
    unsigned char  unk_a2;
    unsigned char  unk_a3;
    unsigned char  unk_a4;
    unsigned char  unk_a5;
    unsigned char  unk_a6;
    unsigned char  unk_a7;
    unsigned char  unk_a8;
    unsigned char  unk_a9;
    unsigned char  unk_aa;
    unsigned char  unk_ab;
    unsigned char  unk_ac;
    unsigned char  unk_ad;
    unsigned char  unk_ae;
    unsigned char  unk_af;
    unsigned char  unk_b0;
    unsigned char  unk_b1;
    unsigned char  unk_b2;
    unsigned char  unk_b3;
    unsigned char  unk_b4;
    unsigned char  unk_b5;
    unsigned char  unk_b6;
    unsigned char  unk_b7;
    unsigned char  unk_b8;
    unsigned char  unk_b9;
    unsigned char  unk_ba;
    unsigned char  unk_bb;
    unsigned char  unk_bc;
    unsigned char  unk_bd;
    unsigned char  unk_be;
    unsigned char  unk_bf;
    unsigned char  unk_c0;
    unsigned char  unk_c1;
    unsigned char  unk_c2;
    unsigned char  unk_c3;
    unsigned char  unk_c4;
    unsigned char  unk_c5;
    unsigned char  unk_c6;
    unsigned char  unk_c7;
    unsigned char  unk_c8;
    unsigned char  unk_c9;
    unsigned char  unk_ca;
    unsigned char  unk_cb;
    unsigned char  unk_cc;
    unsigned char  unk_cd;
    unsigned char  unk_ce;
    unsigned char  unk_cf;
    unsigned char  unk_d0;
    unsigned char  unk_d1;
    unsigned char  unk_d2;
    unsigned char  unk_d3;
    unsigned char  unk_d4;
    unsigned char  unk_d5;
    unsigned char  unk_d6;
    unsigned char  unk_d7;
    unsigned char  unk_d8;
    unsigned char  unk_d9;
    unsigned char  unk_da;
    unsigned char  unk_db;
    unsigned char  unk_dc;
    unsigned char  unk_dd;
    unsigned char  unk_de;
    unsigned char  unk_df;
    unsigned char  unk_e0;
    unsigned char  unk_e1;
    unsigned char  unk_e2;
    unsigned char  unk_e3;
    unsigned char  unk_e4;
    unsigned char  unk_e5;
    unsigned char  unk_e6;
    unsigned char  unk_e7;
    unsigned char  unk_e8;
    unsigned char  unk_e9;
    unsigned char  unk_ea;
    unsigned char  unk_eb;
    unsigned char  unk_ec;
    unsigned char  unk_ed;
    unsigned char  unk_ee;
    unsigned char  unk_ef;
    unsigned char  unk_f0;
    unsigned char  unk_f1;
    unsigned char  unk_f2;
    unsigned char  unk_f3;
    unsigned char  unk_f4;
    unsigned char  unk_f5;
    unsigned char  unk_f6;
    unsigned char  unk_f7;
    unsigned char  unk_f8;
    unsigned char  unk_f9;
    unsigned char  unk_fa;
    unsigned char  unk_fb;
    unsigned char  unk_fc;
    unsigned char  unk_fd;
    unsigned char  unk_fe;
    unsigned char  unk_ff;
    unsigned char  unk_100;
    unsigned char  unk_101;
    unsigned char  unk_102;
    unsigned char  unk_103;
    unsigned char  unk_104;
    unsigned char  unk_105;
    unsigned char  unk_106;
    unsigned char  unk_107;
    unsigned char  unk_108;
    unsigned char  unk_109;
    unsigned char  unk_10a;
    unsigned char  unk_10b;
    unsigned char  unk_10c;
    unsigned char  unk_10d;
    unsigned char  unk_10e;
    unsigned char  unk_10f;
    unsigned char  unk_110;
    unsigned char  unk_111;
    unsigned char  unk_112;
    unsigned char  unk_113;
    unsigned char  unk_114;
    unsigned char  unk_115;
    unsigned char  unk_116;
    unsigned char  unk_117;
    unsigned char  unk_118;
    unsigned char  unk_119;
    unsigned char  unk_11a;
    unsigned char  unk_11b;
    unsigned char  unk_11c;
    unsigned char  unk_11d;
    unsigned char  unk_11e;
    unsigned char  unk_11f;
    unsigned char  unk_120;
    unsigned char  unk_121;
    unsigned char  unk_122;
    unsigned char  unk_123;
    unsigned char  unk_124;
    unsigned char  unk_125;
    unsigned char  unk_126;
    unsigned char  unk_127;
    unsigned char  unk_128;
    unsigned char  unk_129;
    unsigned char  unk_12a;
    unsigned char  unk_12b;
    unsigned char  unk_12c;
    unsigned char  unk_12d;
    unsigned char  unk_12e;
    unsigned char  unk_12f;
    unsigned char  unk_130;
    unsigned char  unk_131;
    unsigned char  unk_132;
    unsigned char  unk_133;
    unsigned char  unk_134;
    unsigned char  unk_135;
    unsigned char  unk_136;
    unsigned char  unk_137;
    unsigned char  unk_138;
    unsigned char  unk_139;
    unsigned char  unk_13a;
    unsigned char  unk_13b;
    unsigned char  unk_13c;
    unsigned char  unk_13d;
    unsigned char  unk_13e;
    unsigned char  unk_13f;
    unsigned char  unk_140;
    unsigned char  unk_141;
    unsigned char  unk_142;
    unsigned char  unk_143;
    unsigned char  unk_144;
    unsigned char  unk_145;
    unsigned char  unk_146;
    unsigned char  unk_147;
    unsigned char  unk_148;
    unsigned char  unk_149;
    unsigned char  unk_14a;
    unsigned char  unk_14b;
    unsigned char  unk_14c;
    unsigned char  unk_14d;
    unsigned char  unk_14e;
    unsigned char  unk_14f;
    unsigned char  unk_150;
    unsigned char  unk_151;
    unsigned char  unk_152;
    unsigned char  unk_153;
    unsigned char  unk_154;
    unsigned char  unk_155;
    unsigned char  unk_156;
    unsigned char  unk_157;
    unsigned char  unk_158;
    unsigned char  unk_159;
    unsigned char  unk_15a;
    unsigned char  unk_15b;
    unsigned char  unk_15c;
    unsigned char  unk_15d;
    unsigned char  unk_15e;
    unsigned char  unk_15f;
    unsigned char  unk_160;
    unsigned char  unk_161;
    unsigned char  unk_162;
    unsigned char  unk_163;
    unsigned char  unk_164;
    unsigned char  unk_165;
    unsigned char  unk_166;
    unsigned char  unk_167;
    unsigned char  unk_168;
    unsigned char  unk_169;
    unsigned char  unk_16a;
    unsigned char  unk_16b;
    unsigned char  unk_16c;
    unsigned char  unk_16d;
    unsigned char  unk_16e;
    unsigned char  unk_16f;
    unsigned char  unk_170;
    unsigned char  unk_171;
    unsigned char  unk_172;
    unsigned char  unk_173;
    unsigned char  unk_174;
    unsigned char  unk_175;
    unsigned char  unk_176;
    unsigned char  unk_177;
    unsigned char  unk_178;
    unsigned char  unk_179;
    unsigned char  unk_17a;
    unsigned char  unk_17b;
    unsigned char  unk_17c;
    unsigned char  unk_17d;
    unsigned char  unk_17e;
    unsigned char  unk_17f;
    unsigned char  unk_180;
    unsigned char  unk_181;
    unsigned char  unk_182;
    unsigned char  unk_183;
    unsigned char  unk_184;
    unsigned char  unk_185;
    unsigned char  unk_186;
    unsigned char  unk_187;
    unsigned char  unk_188;
    unsigned char  unk_189;
    unsigned char  unk_18a;
    unsigned char  unk_18b;
    unsigned char  unk_18c;
    unsigned char  unk_18d;
    unsigned char  unk_18e;
    unsigned char  unk_18f;
    unsigned char  unk_190;
    unsigned char  unk_191;
    unsigned char  unk_192;
    unsigned char  unk_193;
    unsigned char  unk_194;
    unsigned char  unk_195;
    unsigned char  unk_196;
    unsigned char  unk_197;
    unsigned char  unk_198;
    unsigned char  unk_199;
    unsigned char  unk_19a;
    unsigned char  unk_19b;
    unsigned char  unk_19c;
    unsigned char  unk_19d;
    unsigned char  unk_19e;
    unsigned char  unk_19f;
    unsigned char  unk_1a0;
    unsigned char  unk_1a1;
    unsigned char  unk_1a2;
    unsigned char  unk_1a3;
    unsigned char  unk_1a4;
    unsigned char  unk_1a5;
    unsigned char  unk_1a6;
    unsigned char  unk_1a7;
    unsigned char  unk_1a8;
    unsigned char  unk_1a9;
    unsigned char  unk_1aa;
    unsigned char  unk_1ab;
    unsigned char  unk_1ac;
    unsigned char  unk_1ad;
    unsigned char  unk_1ae;
    unsigned char  unk_1af;
    unsigned char  unk_1b0;
    unsigned char  unk_1b1;
    unsigned char  unk_1b2;
    unsigned char  unk_1b3;
    unsigned char  unk_1b4;
    unsigned char  unk_1b5;
    unsigned char  unk_1b6;
    unsigned char  unk_1b7;
    unsigned char  unk_1b8;
    unsigned char  unk_1b9;
    unsigned char  unk_1ba;
    unsigned char  unk_1bb;
    unsigned char  unk_1bc;
    unsigned char  unk_1bd;
    unsigned char  unk_1be;
    unsigned char  unk_1bf;
    unsigned char  unk_1c0;
    unsigned char  unk_1c1;
    unsigned char  unk_1c2;
    unsigned char  unk_1c3;
    unsigned char  unk_1c4;
    unsigned char  unk_1c5;
    unsigned char  unk_1c6;
    unsigned char  unk_1c7;
    unsigned char  unk_1c8;
    unsigned char  unk_1c9;
    unsigned char  unk_1ca;
    unsigned char  unk_1cb;
    unsigned char  unk_1cc;
    unsigned char  unk_1cd;
    unsigned char  unk_1ce;
    unsigned char  unk_1cf;
    unsigned char  unk_1d0;
    unsigned char  unk_1d1;
    unsigned char  unk_1d2;
    unsigned char  unk_1d3;
    unsigned char  unk_1d4;
    unsigned char  unk_1d5;
    unsigned char  unk_1d6;
    unsigned char  unk_1d7;
    unsigned char  unk_1d8;
    unsigned char  unk_1d9;
    unsigned char  unk_1da;
    unsigned char  unk_1db;
    unsigned char  unk_1dc;
    unsigned char  unk_1dd;
    unsigned char  unk_1de;
    unsigned char  unk_1df;
    unsigned char  unk_1e0;
    unsigned char  unk_1e1;
    unsigned char  unk_1e2;
    unsigned char  unk_1e3;
    unsigned char  unk_1e4;
    unsigned char  unk_1e5;
    unsigned char  unk_1e6;
    unsigned char  unk_1e7;
    unsigned char  unk_1e8;
    unsigned char  unk_1e9;
    unsigned char  unk_1ea;
    unsigned char  unk_1eb;
    unsigned char  unk_1ec;
    unsigned char  unk_1ed;
    unsigned char  unk_1ee;
    unsigned char  unk_1ef;
    unsigned char  unk_1f0;
    unsigned char  unk_1f1;
    unsigned char  unk_1f2;
    unsigned char  unk_1f3;
    unsigned char  unk_1f4;
    unsigned char  unk_1f5;
    unsigned char  unk_1f6;
    unsigned char  unk_1f7;
    unsigned char  unk_1f8;
    unsigned char  unk_1f9;
    unsigned char  unk_1fa;
    unsigned char  unk_1fb;
    unsigned char  unk_1fc;
    unsigned char  unk_1fd;
    unsigned char  unk_1fe;
    unsigned char  unk_1ff;
    unsigned char  unk_200;
    unsigned char  unk_201;
    unsigned char  unk_202;
    unsigned char  unk_203;
    unsigned char  unk_204;
    unsigned char  unk_205;
    unsigned char  unk_206;
    unsigned char  unk_207;
    unsigned char  unk_208;
    unsigned char  unk_209;
    unsigned char  unk_20a;
    unsigned char  unk_20b;
    unsigned char  unk_20c;
    unsigned char  unk_20d;
    unsigned char  unk_20e;
    unsigned char  unk_20f;
    unsigned char  unk_210;
    unsigned char  unk_211;
    unsigned char  unk_212;
    unsigned char  unk_213;
    unsigned char  unk_214;
    unsigned char  unk_215;
    unsigned char  unk_216;
    unsigned char  unk_217;
    unsigned char  unk_218;
    unsigned char  unk_219;
    unsigned char  unk_21a;
    unsigned char  unk_21b;
    unsigned char  unk_21c;
    unsigned char  unk_21d;
    unsigned char  unk_21e;
    unsigned char  unk_21f;
    unsigned char  unk_220;
    unsigned char  unk_221;
    unsigned char  unk_222;
    unsigned char  unk_223;
    unsigned char  unk_224;
    unsigned char  unk_225;
    unsigned char  unk_226;
    unsigned char  unk_227;
    unsigned char  unk_228;
    unsigned char  unk_229;
    unsigned char  unk_22a;
    unsigned char  unk_22b;
    unsigned char  unk_22c;
    unsigned char  unk_22d;
    unsigned char  unk_22e;
    unsigned char  unk_22f;
    unsigned char  unk_230;
    unsigned char  unk_231;
    unsigned char  unk_232;
    unsigned char  unk_233;
    unsigned char  unk_234;
    unsigned char  unk_235;
    unsigned char  unk_236;
    unsigned char  unk_237;
    unsigned char  unk_238;
    unsigned char  unk_239;
    unsigned char  unk_23a;
    unsigned char  unk_23b;
    unsigned char  unk_23c;
    unsigned char  unk_23d;
    unsigned char  unk_23e;
    unsigned char  unk_23f;
    unsigned char  unk_240;
    unsigned char  unk_241;
    unsigned char  unk_242;
    unsigned char  unk_243;
    unsigned char  unk_244;
    unsigned char  unk_245;
    unsigned char  unk_246;
    unsigned char  unk_247;
    unsigned char  unk_248;
    unsigned char  unk_249;
    unsigned char  unk_24a;
    unsigned char  unk_24b;
    unsigned char  unk_24c;
    unsigned char  unk_24d;
    unsigned char  unk_24e;
    unsigned char  unk_24f;
} CLS_MOJI_W;

typedef struct CLS_BG_W {
    CLS_W            header;
    float            tx, ty, tz;
    short            rx, ry, rz;
    float            sx, sy, sz;
    float            time;
    unsigned int     AModel;
    unsigned int     init_glist;
    WAVE_W           SegWave[6];
    unsigned char    unk_64;
    char             unk_65;
    unsigned char    unk_66;
    unsigned char    unk_67;
    int              unk_68;
    int              unk_6c;
    float            unk_70;
    struct CLS_BG_W* left;
    struct CLS_BG_W* right;
    unsigned char    unk_7c[2];
    short            unk_7e;
    void*            unk_80;
    unsigned short   unk_84;
    unsigned char    unk_86;
    unsigned char    unk_87;
    float            unk_88;
    float            unk_8c;
    float            unk_90;
    struct CLS_BG_W* prev;
} CLS_BG_W;

typedef struct CLS_GBG_W {
    CLS_W          header;
    int            unk_8;
    unsigned short wave_no;
    unsigned short flags;
    short          texture_width, texture_height;
    float          u, v;
    float          x, y;
    float          w, h;
    unsigned char  alpha;
    short          min_x, min_y;
    short          max_x, max_y;
    unsigned char* texture_data;
    unsigned char* palette_data;
    unsigned short bits_per_pixel;
} CLS_GBG_W;

typedef struct TASK_W {
    struct TASK_W* next;
    struct TASK_W* unk_4;
    void          (*exec[3])(struct TASK_W*, struct CLS_W*);
    void          (*prev_exec)(struct TASK_W*, struct CLS_W*);
    void*          unk_18;
    void*          unk_1c;
    unsigned short priority;
    unsigned short unk_22;
    unsigned short timer;
    WAVE_W         wave;
    unsigned char  unk_30;
    unsigned char  unk_31;
    unsigned char  unk_32;
    unsigned char  unk_33;
    unsigned int   unk_34;
    unsigned int   unk_38;
    unsigned short unk_3c;
    unsigned short unk_3e;
    unsigned short unk_40;
    unsigned short unk_42;
    unsigned char  unk_44;
    unsigned char  unk_45;
    unsigned char  unk_46;
    unsigned char  unk_47;
    unsigned int   unk_48;
    unsigned char  unk_4c;
    unsigned char  unk_4d;
    unsigned short unk_4e;
    unsigned short unk_50;
    unsigned short unk_52;
    unsigned int   unk_54;
    unsigned int   unk_58;
} TASK_W;

typedef struct GRAPH_BUF_W {
    Gfx           display_lists[10640];
    Mtx           matrices[540];
    Vp            viewports[4];
    unsigned char unk_1d3c0[600];
    unsigned char unk_1d618[128];
    unsigned char unk_1d698[64];
} GRAPH_BUF_W;

typedef struct CONTROLLER_W {
    unsigned short status;
    unsigned short button_held_down;
    unsigned short button_pressed;
    short          stick_raw_x;
    short          stick_raw_y;
    float          stick_x;
    float          stick_y;
    float          stick_magnitude;
} CONTROLLER_W;

typedef struct CAMERA_REGION_W {
    short         unk_0;
    unsigned char unk_2;
    unsigned char unk_3;
    int           unk_4;
    int           unk_8;
    int           unk_c;
    int           unk_10;
    int           unk_14;
    int           unk_18;
    int           unk_1c;
    int           unk_20;
    int           unk_24;
} CAMERA_REGION_W;

typedef struct TEXT_LABEL_W {
    unsigned char  type;
    unsigned char  unk_1;
    short          x;
    short          y;
    unsigned char  unk_6;
    unsigned char  unk_7;
    unsigned char* string;
    unsigned int   unk_c;
} TEXT_LABEL_W;

typedef struct CLS_GROUP_W {
    CLS_W*        elements[220];
    unsigned char size;
    unsigned char unk_371;
    unsigned char unk_372;
    unsigned char unk_373;
} CLS_GROUP_W;

typedef struct WAVE_REQ_W {
    int            wave_no;
    unsigned char* data;
} WAVE_REQ_W;

typedef struct SYS_W {
    GRAPH_BUF_W     graphics_buffer[2];
    short           current_frame_buffer;
    short           current_graphics_pool;
    short           file_loader_working_graphics_pool;
    short           disable_graphics_tasks;
    short           frames_elapsed;
    unsigned short  fill_color_red;
    unsigned short  fill_color_green;
    unsigned short  fill_color_blue;
    unsigned short  fill_color_alpha;
    unsigned short  frame_buffer_bits_per_pixel;
    short           clear_depth_buffer;
    unsigned char   unk_3adc6[2];
    short           dont_process_draw_lists;
    unsigned char   retraces_per_game_step;
    unsigned char   unk_3adcb;
    unsigned short  retrace_count;
    short           game_loops_count;
    unsigned short  attrack_demo_frames_elapsed;
    unsigned short  unk_3add2;
    unsigned char   stepw;
    unsigned char   stepw_end;
    unsigned char   unk_3add6;
    unsigned char   unk_3add7;
    unsigned char   unk_3add8;
    unsigned char   unk_3add9;
    unsigned char   unk_3adda;
    unsigned char   unk_3addb;
    unsigned char   unk_3addc;
    unsigned char   unk_3addd;
    unsigned char   unk_3adde;
    unsigned char   unk_3addf;
    unsigned char   unk_3ade0;
    unsigned char   unk_3ade1;
    unsigned char   unk_3ade2;
    unsigned char   unk_3ade3;
    unsigned char   intended_room_group;
    unsigned char   unk_3ade5;
    unsigned short  unk_3ade6;
    unsigned int    unk_3ade8;
    unsigned short  unk_3adec;
    unsigned short  unk_3adee;
    unsigned short  unk_3adf0;
    unsigned short  intended_room_id;
    unsigned short  intended_room_group_index;
    unsigned char   current_room_group;
    unsigned char   unk_3adf7;
    unsigned short  current_room_group_index;
    unsigned char   unk_3adfa;
    unsigned char   unk_3adfb;
    unsigned short  unk_3adfc;
    unsigned short  unk_3adfe;
    unsigned short  unk_3ae00;
    unsigned char   unk_3ae02;
    unsigned char   unk_3ae03;
    unsigned int    unk_3ae04;
    unsigned int    unk_3ae08;
    unsigned char   unk_3ae0c;
    unsigned char   unk_3ae0d;
    unsigned char   unk_3ae0e;
    unsigned char   unk_3ae0f;
    unsigned char   unk_3ae10;
    unsigned char   unk_3ae11;
    unsigned char   unk_3ae12;
    unsigned char   unk_3ae13;
    unsigned short  is_controller_pak_connected;
    unsigned short  unk_3ae16;
    unsigned short  unk_3ae18;
    unsigned char   unk_3ae1a;
    unsigned char   unk_3ae1b;
    unsigned int    unk_3ae1c;
    unsigned char   unk_3ae20;
    unsigned char   unk_3ae21;
    unsigned char   unk_3ae22;
    unsigned char   unk_3ae23;
    unsigned short  unk_3ae24;
    unsigned short  unk_3ae26;
    unsigned char   unk_3ae28;
    unsigned char   unk_3ae29;
    unsigned char   unk_3ae2a;
    unsigned char   unk_3ae2b;
    unsigned int    unk_3ae2c;
    unsigned short  unk_3ae30;
    unsigned char   unk_3ae32;
    unsigned char   unk_3ae33;
    unsigned char   unk_3ae34;
    unsigned char   unk_3ae35;
    unsigned char   unk_3ae36;
    unsigned char   unk_3ae37;
    unsigned char   unk_3ae38;
    unsigned char   unk_3ae39;
    unsigned short  unk_3ae3a;
    unsigned int    unk_3ae3c;
    unsigned short  camera_type;
    unsigned char   unk_3ae42;
    unsigned char   unk_3ae43;
    unsigned int    unk_3ae44;
    unsigned int    unk_3ae48;
    unsigned int    unk_3ae4c;
    CAMERA_REGION_W camera_regions[10];
    unsigned short  unk_3afe0;
    unsigned short  unk_3afe2;
    unsigned short  unk_3afe4;
    unsigned short  unk_3afe6;
    unsigned short  unk_3afe8;
    unsigned short  unk_3afea;
    unsigned short  unk_3afec;
    unsigned short  unk_3afee;
    unsigned short  unk_3aff0;
    unsigned short  unk_3aff2;
    unsigned short  unk_3aff4;
    unsigned short  unk_3aff6;
    unsigned short  unk_3aff8;
    unsigned short  unk_3affa;
    unsigned short  unk_3affc;
    unsigned short  unk_3affe;
    unsigned int    unk_3b000;
    unsigned int    unk_3b004;
    unsigned int    unk_3b008;
    unsigned char   unk_3b00c[4];
    unsigned char   unk_3b010;
    unsigned char   unk_3b011;
    unsigned char   unk_3b012;
    unsigned char   unk_3b013;
    void*           unk_3b014;
    unsigned int    unk_3b018;
    unsigned char   unk_3b01c;
    unsigned char   unk_3b01d;
    unsigned short  unk_3b01e;
    short           unk_3b020;
    unsigned short  unk_3b022;
    unsigned short  unk_3b024;
    unsigned char   unk_3b026;
    unsigned char   unk_3b027;
    unsigned char   unk_3b028;
    unsigned char   unk_3b029;
    unsigned char   unk_3b02a;
    unsigned char   unk_3b02b;
    unsigned short  unk_3b02c;
    unsigned char   unk_3b02e;
    unsigned char   unk_3b02f;
    unsigned int    unk_3b030;
    unsigned int    unk_3b034;
    unsigned char   unk_3b038;
    unsigned char   unk_3b039;
    unsigned char   unk_3b03a;
    unsigned char   unk_3b03b;
    void*           load_files_function;
    unsigned int    unk_3b040;
    unsigned char   unk_3b044[4];
    unsigned int    unk_3b048;
    unsigned char   unk_3b04c[4];
    unsigned char   unk_3b050[4];
    unsigned int    unk_3b054;
    unsigned char   unk_3b058[28];
    unsigned char   file_requests_count;
    unsigned char   unk_3b075;
    unsigned char   unk_3b076;
    unsigned char   unk_3b077;
    CONTROLLER_W    controller[5];
    CONTROLLER_W    controller_combined;
    unsigned int    unk_3b108[24];
    TEXT_LABEL_W    text_label[80];
    CLS_MOJI_W      unknown_heap[2];
    unsigned char   unknown_data[524288];
    CLS_GBG_W       skybox_heap[2];
    CLS_BG_W        object_heap[192];
    unsigned short  unk_c2d90;
    unsigned char   unk_c2d92;
    unsigned char   unk_c2d93;
    CLS_2D_W        sprite_heap[24];
    CLS_GROUP_W     draw_lists[12];
    unsigned char   stop_processing_draw_lists;
    unsigned char   unk_c5d05;
    unsigned short  unk_c5d06;
    unsigned short  unk_c5d08;
    unsigned short  unk_c5d0a;
    unsigned short  unk_c5d0c;
    unsigned char   unk_c5d0e;
    unsigned char   unk_c5d0f;
    unsigned int    unk_c5d10;
    unsigned char   unk_c5d14[4];
    short           unknown_rgba16_buffer[256];
    unsigned short  unk_c5f18[16];
    unsigned int    unk_c5f38[16];
    void*           unk_c5f78;
    unsigned int    unk_c5f7c;
    WAVE_REQ_W*     file_requests_table[8];
    unsigned char   decompression_buffer[8192];
    unsigned char   unk_c7fa0;
    unsigned char   unk_c7fa1;
    unsigned char   unk_c7fa2;
    unsigned char   unk_c7fa3;
    AMEM_W          memory_blocks[1920];
    unsigned char   unk_cf7a4[12];
    int*            unk_cf7b0;
    unsigned char   unk_cf7b4[88];
    int             tlb_physical_addresses[32];
    unsigned char   player_exists;
    unsigned char   unk_cf88d;
    unsigned short  unk_cf88e;
    unsigned short  unk_cf890;
    unsigned char   unk_cf892;
    unsigned char   unk_cf893;
    unsigned int    unk_cf894;
    unsigned char   unk_cf898;
    unsigned char   unk_cf899;
    unsigned char   unk_cf89a;
    unsigned char   unk_cf89b;
    unsigned int    unk_cf89c;
    unsigned char   unk_cf8a0;
    unsigned char   unk_cf8a1;
    unsigned char   unk_cf8a2;
    unsigned char   unk_cf8a3;
    unsigned char   unk_cf8a4[12];
    unsigned int    unk_cf8b0;
    unsigned char   unk_cf8b4;
    unsigned char   unk_cf8b5;
    unsigned char   unk_cf8b6;
    unsigned char   unk_cf8b7;
    void*           unk_cf8b8;
    void*           unk_cf8bc;
    void*           unk_cf8c0;
    void*           unk_cf8c4;
    void*           unk_cf8c8;
    void*           unk_cf8cc;
    void*           unk_cf8d0;
    void*           unk_cf8d4;
    void*           player_manager_task;
    void*           dummy_task;
    void*           actor_manager_task;
    void*           skybox_manager_task;
    void*           room_lighting_task;
    void*           unk_cf8ec;
    void*           hud_graphics_task;
    void*           room_graphics_task;
    void*           unk_cf8f8;
    unsigned int    unk_cf8fc;
    unsigned int    unk_cf900;
    unsigned int    unk_cf904;
} SYS_W;

extern SYS_W  D_8008CCC0_8D8C0;
extern SYS_W* D_8015C5C8_15D1C8;

#endif // COMMON_H
